### PR TITLE
Add ready request and response

### PR DESCRIPTION
**Pull request by 1-alex98**
In preparation for the tournament service

### CODE REVIEW

**Comment by Brutus5000** [comment]
@1-alex98  Is this a new message that is not on the server yet? I have never seen it.

**Comment by 1-alex98** [comment]
Related to https://github.com/FAForever/server/issues/675

**Comment by Sheikah45** [comment]
Hmmm wasn't there a ready message already that had been added for the matchmaker?

**Comment by 1-alex98** [comment]
@Sheikah45 yes and no.

There is a ReadyPartyRequest class. It is used nowhere. The name is unfitting because there is no party in tournament context. It also does not have the needed "featured_mod" field for the client to update the featured mod in advance. 

I can delete that class if you want me too. Using it seems less of an option.

**Comment by Sheikah45** [comment]
Yes I know it isn't used anywhere since it hasn't been implemented client or server side yet so was just thinking that what you have could either use it or replace it for implementation.

**Comment by 1-alex98** [comment]
Should I delete the class?

**Comment by Sheikah45** [comment]
Yeah probably for the best and if we ever implement it we can make the server use the one you have created

**Comment by 1-alex98** [comment]
> Yeah probably for the best and if we ever implement it we can make the server use the one you have created

Probably not tho otherwise client would think it is about a tournament game

**Comment by Sheikah45** [comment]
> > Yeah probably for the best and if we ever implement it we can make the server use the one you have created
> 
> Probably not tho otherwise client would think it is about a tournament game

Well there is nothing tournament specific about the message. The only tournament specific thing is the client i18n but that isnt in the protocol

**Comment by 1-alex98** [comment]
> > > Yeah probably for the best and if we ever implement it we can make the server use the one you have created
> > 
> > 
> > Probably not tho otherwise client would think it is about a tournament game
> 
> Well there is nothing tournament specific about the message. The only tournament specific thing is the client i18n but that isnt in the protocol

True...

**Comment by 1-alex98** [comment]
@Sheikah45 ok?

**Review by Brutus5000 — APPROVED** [review]

**Review by Sheikah45 — APPROVED** [review]

**Comment by 1-alex98** [comment]
Please merge

**Comment by 1-alex98** [comment]
@Sheikah45

**Pull request merged**
